### ISSUE TITLE
About the paper

### ISSUE THREAD

**Issue by jasdasdf** [echocatzh/Demo-of-DeepComplexAEC#1]
hi,  Shiming
Great job. Is it a real-time system?
By the way, can you share the paper on this project?
thanks.

**Comment by echocatzh** [comment]
Hi, jasdasdf
Thank you for your attention to our work. This is a real-time AEC, but it is still in the draft review stage. If there is any new information, I will concat you.

**Comment by jasdasdf** [comment]
> Hi, jasdasdf
> Thank you for your attention to our work. This is a real-time AEC, but it is still in the draft review stage. If there is any new information, I will concat you.

OK，that's very nice of you, looking forward to your good news.

**Comment by echocatzh** [comment]
> > Hi, jasdasdf
> > Thank you for your attention to our work. This is a real-time AEC, but it is still in the draft review stage. If there is any new information, I will concat you.
> 
> OK，that's very nice of you, looking forward to your good news.

https://arxiv.org/abs/2106.07577
